# Generated by Django 2.0 on 2020-10-29 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_post_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
    ]
